-- AlterTable
ALTER TABLE `predmet` ADD COLUMN `datumOtvaranja` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `faza` ENUM('ISTRAGA', 'PRIKUPLJANJE_DOKAZA', 'SUDJENJE') NOT NULL DEFAULT 'ISTRAGA',
    ADD COLUMN `status` ENUM('AKTIVAN', 'ZATVOREN') NOT NULL DEFAULT 'AKTIVAN';
